name: AKS Deployment

on:
  workflow_dispatch: ~
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Python
      uses: actions/setup-python@v4.3.0
      with:
        # Version range or exact version of Python or PyPy to use, using SemVer's version range syntax. Reads from .python-version if unset.
        python-version: 3.8.x
#     - name: python build
#       run: python build -c release
      
    - name: docker build
      run: docker build --pull --rm -f "dockerfile" -t testrepo:'${{github.sha}}' "."
      
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        # Container registry username
        username: testacrzaki
        # Container registry password
        password: ND4ZyHYBJP=eVgbnGIEIvl49J=p4UVMs
        # Container registry server url
        login-server: https://index.docker.io/v1/
        
    - name: tag docker image
      run: docker tag testrepo:'${{github.sha}}' testacrzaki.azurecr.io/testrepo:'${{github.sha}}'
      
    - name: push docker image
      run: docker push testacrzaki.azurecr.io/testrepo:'${{github.sha}}'
