name: AKS Deployment

on:
  workflow_dispatch: ~
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Python
      uses: actions/setup-python@v4.3.0
      with:
        # Version range or exact version of Python or PyPy to use, using SemVer's version range syntax. Reads from .python-version if unset.
        python-version: 3.8.x
#     - name: python build
#       run: python build -c release
      
    - name: docker build
      run: docker build --pull --rm -f "dockerfile" -t testrepo:'${{github.sha}}' "."
      
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        # Container registry username
        username: testacrzaki
        # Container registry password
        password: ND4ZyHYBJP=eVgbnGIEIvl49J=p4UVMs
        # Container registry server url
        login-server: testacrzaki.azurecr.io
        
    - name: tag docker image
      run: docker tag testrepo:'${{github.sha}}' testacrzaki.azurecr.io/testrepo:'${{github.sha}}'
      
    - name: push docker image
      run: docker push testacrzaki.azurecr.io/testrepo:'${{github.sha}}'
      
    - name: Azure Login
      uses: Azure/login@v1.4.6
      with:
        # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
        creds: '${{secrets.AZURE_CREDENTIALS}}'
    - name: Azure Kubernetes set context
      uses: Azure/aks-set-context@v3
      with:
        # Resource Group Name
        resource-group: testgroup
        # AKS Cluster Name
        cluster-name: testcluster
        # AKS Cluster Subscription
        admin: true
        
    - name: Create secret in Kubernetes cluster
      uses: Azure/k8s-create-secret@v3.0
      with:
        secret-name: docker-image-pull-request
        # Container Registry URL
        container-registry-url: testacrzaki.azurecr.io
        # Container Registry user name
        container-registry-username: testacrzaki
        # Container Registry password
        container-registry-password: ND4ZyHYBJP=eVgbnGIEIvl49J=p4UVMs
        secret-type: acr-registry
        
    - name: Deploy to Kubernetes cluster
      uses: Azure/k8s-deploy@v4
      with:
        # Path to the manifest files which will be used for deployment.
        manifests: k8s/deployment.yml
        # Fully qualified resource URL of the image(s) to be used for substitutions on the manifest files Example: contosodemo.azurecr.io/helloworld:test
        images: testacrzaki.azurecr.io/testrepo:'${{github.sha}}'
        # Name of a docker-registry secret that has already been set up within the cluster. Each of these secret names are added under imagePullSecrets field for the workloads found in the input manifest files
        imagepullsecrets: docker-image-pull-request
        # deploy, promote, or reject
        action: deploy
 
